tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/portable-ruby"

brew "nmap"
brew "python@3.11"
brew "tmux"
brew "zsh-completions"

cask "macfuse"
cask "visual-studio-code"

vscode "donjayamanne.python-environment-manager"
vscode "donjayamanne.python-extension-pack"
vscode "eamodio.gitlens"
vscode "jebbs.plantuml"
vscode "Mebrahtom.plantumlpreviewer"
vscode "mhutchie.git-graph"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-ssh-edit"
vscode "ms-vscode.remote-explorer"
vscode "myml.vscode-markdown-plantuml-preview"
vscode "VisualStudioExptTeam.vscodeintellicode"