#!/bin/sh
#
# Usage:
#
#    sh install.sh
#
# Environment variables: VERBOSE, CP, LN, MKDIR, RM, DIRNAME.
#
#    env VERBOSE=1 sh install.sh
#
# DO NOT EDIT THIS FILE
# 
# This file is generated by rcm(7) as:
#
#   rcup -g -B 0
#
# To update it, re-run the above command.
#
: ${VERBOSE:=0}
: ${CP:=/bin/cp}
: ${LN:=/bin/ln}
: ${MKDIR:=/bin/mkdir}
: ${RM:=/bin/rm}
: ${DIRNAME:=/usr/bin/dirname}
verbose() {
  if [ "$VERBOSE" -gt 0 ]; then
    echo "$@"
  fi
}
handle_file_cp() {
  if [ -e "$2" ]; then
    printf "%s " "overwrite $2? [yN]"
    read overwrite
    case "$overwrite" in
      y)
        $RM -rf "$2"
        ;;
      *)
        echo "skipping $2"
        return
        ;;
    esac
  fi
  verbose "'$1' -> '$2'"
  $MKDIR -p "$($DIRNAME "$2")"
  $CP -R "$1" "$2"
}
handle_file_ln() {
  if [ -e "$2" ]; then
    printf "%s " "overwrite $2? [yN]"
    read overwrite
    case "$overwrite" in
      y)
        $RM -rf "$2"
        ;;
      *)
        echo "skipping $2"
        return
        ;;
    esac
  fi
  verbose "'$1' -> '$2'"
  $MKDIR -p "$($DIRNAME "$2")"
  $LN -sf "$1" "$2"
}
handle_file_ln "/home/vfrc29/.dotfiles/bash_aliases" "/home/vfrc29/.bash_aliases"
handle_file_ln "/home/vfrc29/.dotfiles/bashrc" "/home/vfrc29/.bashrc"
handle_file_ln "/home/vfrc29/.dotfiles/config/Code/User/settings.json" "/home/vfrc29/.config/Code/User/settings.json"
handle_file_ln "/home/vfrc29/.dotfiles/gitconfig" "/home/vfrc29/.gitconfig"
handle_file_ln "/home/vfrc29/.dotfiles/gitignore" "/home/vfrc29/.gitignore"
handle_file_ln "/home/vfrc29/.dotfiles/local/bin/replace" "/home/vfrc29/.local/bin/replace"
handle_file_ln "/home/vfrc29/.dotfiles/local/bin/tat" "/home/vfrc29/.local/bin/tat"
handle_file_ln "/home/vfrc29/.dotfiles/profile" "/home/vfrc29/.profile"
handle_file_ln "/home/vfrc29/.dotfiles/rcrc" "/home/vfrc29/.rcrc"
handle_file_ln "/home/vfrc29/.dotfiles/rspec" "/home/vfrc29/.rspec"
handle_file_ln "/home/vfrc29/.dotfiles/tmux.conf" "/home/vfrc29/.tmux.conf"
