#!/bin/sh

system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then
  VSCODE_SETTINGS_DIR="$HOME/.config/Code/User"
  MY_VSCODE_SETTINGS_MAC="$HOME/Library/Application Support/Code/User"
  echo "VSCode config link"
  for file in $VSCODE_SETTINGS_DIR/* ; do  
    if ! ln -v "$file" "$MY_VSCODE_SETTINGS_MAC" ; then
      echo "you can try"
      echo "  ln -f \"$file\" \"$MY_VSCODE_SETTINGS_MAC\""
    fi
  done
  echo "Done"
fi

if [ "$system_type" = "Darwin" ]; then

  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  fi

  if [ -f "$HOME/.Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --global
  fi
fi

if [ -f "$(which apt-get)" ]; then
  echo Install utils throught apt
  sudo apt install -y renameutils exa fzf bat tmux zsh-antigen
fi

if [ ! -f "$(which starship)" ]; then
  curl -sS https://starship.rs/install.sh | sh
fi
