#!/bin/sh

system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then
  MY_VSCODE_SETTINGS_MAC="$HOME/Library/Application Support/Code/User/settings.json"
  if [ -f "$MY_VSCODE_SETTINGS_MAC" ]; then
    echo "VSCode config already exist, $MY_VSCODE_SETTINGS_MAC"
    echo "if you want to override run"
    echo "ln -f \"$HOME/.config/Code/User/settings.json\" \"$MY_VSCODE_SETTINGS_MAC\""
 else
    ln "$HOME/.config/Code/User/settings.json" "$MY_VSCODE_SETTINGS_MAC" && echo "VSCode config copied"
  fi
fi

if [ "$system_type" = "Darwin" ]; then

  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  fi

  if [ -f "$HOME/.Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --global
  fi
fi

if [ -f "$(which apt-get)" ]; then
  echo Install utils throught apt
  sudo apt install -y renameutils exa fzf bat tmux zsh-antigen
fi

if [ ! -f "$(which starship)" ]; then
  echo "Install starship"
  curl -sS https://starship.rs/install.sh | sh
else
  echo "starship already instaled"
fi

if [ ! -f "$HOME/.config/tmux/plugins/tpm/README.md" ]; then
  echo Install tpm
  git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm
else
  echo "tpm already instaled"
fi

